### ISSUE TITLE
Testing with Mariadb GALERA

### ISSUE THREAD

**Issue by ArgiSanchezAguilera** [numtel/meteor-mysql#47]
I like so much reactive mysql and 
I am trying to testing with mariadb galera for high availability and load balancer HAProxy in front ... 
all nodes have: max_binlog_size  = 100M  in config file but after a few seconds crash with this error:
(perhaps then jumping between different logs nodes it's the problem ...) 

Error: ER_MASTER_FATAL_ERROR_READING_BINLOG: log event entry exceeded max_allowed_packet; Increase max_allowed_packet on master; the first event 'mariadb-bin.000001' at 3275, the last event read from 'mariadb-bin.000001' at 3275, the last byte read from 'mariadb-bin.000001' at 3294.
W20151107-21:33:06.855(1)? (STDERR)     at Binlog.Sequence._packetToError (/home/argi/.meteor/packages/numtel_mysql/.1.0.3.gmblep++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
W20151107-21:33:06.855(1)? (STDERR)     at Binlog.Sequence.ErrorPacket (/home/argi/.meteor/packages/numtel_mysql/.1.0.3.gmblep++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:109:17)
W20151107-21:33:06.855(1)? (STDERR)     at Protocol._parsePacket (/home/argi/.meteor/packages/numtel_mysql/.1.0.3.gmblep++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20151107-21:33:06.855(1)? (STDERR)     at Parser.write (/home/argi/.meteor/packages/numtel_mysql/.1.0.3.gmblep++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
W20151107-21:33:06.855(1)? (STDERR)     at Protocol.write (/home/argi/.meteor/packages/numtel_mysql/.1.0.3.gmblep++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
W20151107-21:33:06.855(1)? (STDERR)     at Socket.<anonymous> (/home/argi/.meteor/packages/numtel_mysql/.1.0.3.gmblep++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:82:28)
W20151107-21:33:06.855(1)? (STDERR)     at Socket.emit (events.js:95:17)
W20151107-21:33:06.856(1)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20151107-21:33:06.856(1)? (STDERR)     at Socket.emit (events.js:92:17)
W20151107-21:33:06.856(1)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20151107-21:33:06.856(1)? (STDERR)     --------------------

**Comment by vlasky** [comment]
Beware - MariaDB's binary log is not fully compatible with MySQL's, so the binary log following code implemented by the zongji package is getting confused.

If you want Galera, I would recommend that you test Meteor with Persona Server XtraDB cluster, which has a Galera-enabled version:

https://www.percona.com/downloads/Percona-XtraDB-Cluster-56/LATEST/

**Comment by ArgiSanchezAguilera** [comment]
Thanks vlasky I will try .... but I think the problem is that HAProxy is giving different node log files in each request ... with one mariadb only works great ...
