### ISSUE TITLE
Error when creating a new LiveMysql

### ISSUE THREAD

**Issue by 3thanZ** [numtel/meteor-mysql#57]
Hi,

I get the error **`TypeError: Column must be greater than or equal to 0, got -14`** when I execute the code below:

```
var liveDb = new LiveMysql({
	host: 'localhost',
	user: 'redmine',
	password: 'redmine',
	database: 'redmine',
	serverId: 1,
	minInterval: 200
});

var closeAndExit = function() {
	// liveDb.end();
	process.exit();
}; 

// Close connections on hot code push
process.on('SIGTERM', closeAndExit);
// Close connections on exit (ctrl + c)
process.on('SIGINT', closeAndExit);
```

I'm running mysql:
```
$ ./mysql --version
./mysql  Ver 14.14 Distrib 5.5.38, for osx10.6 (i386) using  EditLine wrapper
```

Please advise if you have faced a similar issue. The stacktrace is as below:

```
=> Exited with code: 8
I20160107-15:34:17.402(8)? { [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
I20160107-15:34:17.404(8)? { [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
I20160107-15:34:17.404(8)? { [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
W20160107-15:34:17.935(8)? (STDERR) 
W20160107-15:34:17.935(8)? (STDERR) /Users/ethans/.meteor/packages/numtel_mysql/.1.0.3.u1roy7++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Parser.js:82
W20160107-15:34:17.935(8)? (STDERR)         throw err;
W20160107-15:34:17.935(8)? (STDERR)               ^
W20160107-15:34:17.953(8)? (STDERR) TypeError: Column must be greater than or equal to 0, got -14
W20160107-15:34:17.954(8)? (STDERR)     at SourceMapConsumer_findMapping [as _findMapping] (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map/lib/source-map/source-map-consumer.js:281:15)
W20160107-15:34:17.954(8)? (STDERR)     at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map/lib/source-map/source-map-consumer.js:310:26)
W20160107-15:34:17.954(8)? (STDERR)     at mapSourcePosition (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:160:42)
W20160107-15:34:17.954(8)? (STDERR)     at wrapCallSite (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:295:20)
W20160107-15:34:17.954(8)? (STDERR)     at wrapCallSite (/Users/ethans/Desktop/dk/dk-int-projects-tracker/trunk/src/.meteor/local/build/programs/server/boot.js:75:15)
W20160107-15:34:17.954(8)? (STDERR)     at /Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:330:26
W20160107-15:34:17.955(8)? (STDERR)     at Array.map (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:448:1)
W20160107-15:34:17.955(8)? (STDERR)     at Function.prepareStackTrace (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:329:24)
W20160107-15:34:17.955(8)? (STDERR)     at Handshake.Sequence._addLongStackTrace (/Users/ethans/.meteor/packages/numtel_mysql/.1.0.3.u1roy7++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Sequence.js:67:42)
W20160107-15:34:17.955(8)? (STDERR)     at Handshake.Sequence.end (/Users/ethans/.meteor/packages/numtel_mysql/.1.0.3.u1roy7++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:10)
```

**Comment by tvogels** [comment]
I have exactly the same problem. I believe it has something to do with the Node version.
