### ISSUE TITLE
Getting The Following Errors with mysql

### ISSUE THREAD

**Issue by Topol** [numtel/meteor-mysql#6]
I20150218-01:33:02.258(5.5)? ** You've set up some data subscriptions with Meteor.publish(), but
I20150218-01:33:02.260(5.5)? ** you still have autopublish turned on. Because autopublish is still
I20150218-01:33:02.260(5.5)? ** on, your Meteor.publish() calls won't have much effect. All data
I20150218-01:33:02.260(5.5)? ** will still be sent to all clients.
I20150218-01:33:02.260(5.5)? **
I20150218-01:33:02.260(5.5)? ** Turn off autopublish by removing the autopublish package:
I20150218-01:33:02.261(5.5)? **
I20150218-01:33:02.261(5.5)? **   $ meteor remove autopublish
I20150218-01:33:02.261(5.5)? **
I20150218-01:33:02.261(5.5)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150218-01:33:02.261(5.5)? ** for each collection that you want clients to see.
I20150218-01:33:02.261(5.5)? 
W20150218-01:33:02.383(5.5)? (STDERR) 
W20150218-01:33:02.383(5.5)? (STDERR) /private/var/folders/jk/jf0vd73n24n6yfv0cn1v12c00000gn/T/meteor-test-run1mbn73v/.meteor/local/isopacks/numtel_mysql/npm/node_modules/mysql/lib/protocol/Parser.js:82
W20150218-01:33:02.383(5.5)? (STDERR)         throw err;
W20150218-01:33:02.383(5.5)? (STDERR)               ^
W20150218-01:33:02.383(5.5)? (STDERR) Error: ER_NO_BINARY_LOGGING: You are not using binary logging

**Comment by Topol** [comment]
You are not using binary logging. Is this something to do with mysql settings

**Comment by numtel** [comment]
Looks like you need to enable the binary log. Please follow the instructions on the mysql-live-select readme:

https://github.com/numtel/mysql-live-select#installation

**Comment by Topol** [comment]
Hi

I am sorry I am not able to follow these steps and could not find the
error. My mysql is installed using brew in mac.
The file that needs to be updates is /usr/local/opt/mysql/my.cnf.
But when I try to restart the mysql server I get the following alert. Can
you suggest what is going on.
ERROR! The server quit without updating PID file
(/var/run/mysqld/mysqld.pid).

I even followed the steps described in
http://serverfault.com/questions/480889/mysql-server-pid-file-could-not-be-found
but cannot go anywhere. I wonder if you faced something similar.

Best
Arindam

**Comment by Topol** [comment]
Hi

I restarted my system. This fixed the problem of mysql restarting.

But I am still getting the following error... Error: ER_NO_BINARY_LOGGING:
You are not using binary logging

So is this about placing my.cnf file.

Best
Arindam

**Comment by numtel** [comment]
Can you post the contents of your my.cnf file? Also, what version of Mysql are you running?

**Comment by Topol** [comment]
This is inside my.cnf file

# innodb_buffer_pool_size = 128M


# Remove leading # to turn on a very important data integrity option:
logging

# changes to the binary log between backups.

# log_bin


# These are commonly set, remove the # and set as required.

# basedir = .....

# datadir = .....

# port = .....

# server_id = .....

# socket = .....


# binlog config

server-id        = 1

binlog_format    = row

log_bin          = /var/log/mysql/mysql-bin.log

#binlog_do_db     = employees   # optional

expire_logs_days = 10          # optional

max_binlog_size  = 100M        # optional

#pid-file    = /var/run/mysqld/mysqld.pid



# Remove leading # to set options mainly useful for reporting servers.

# The server defaults are faster for transactions and fast SELECTs.

# Adjust sizes as needed, experiment to find the optimal values.

# join_buffer_size = 128M

# sort_buffer_size = 2M

# read_rnd_buffer_size = 2M


sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

**Comment by shipra123456** [comment]
Hello,

I am working on ubuntu and getting problems in binary logging

W20150227-07:06:44.076(0)? (STDERR)           
W20150227-07:06:44.079(0)? (STDERR) /home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Parser.js:82
W20150227-07:06:44.079(0)? (STDERR)         throw err;
W20150227-07:06:44.079(0)? (STDERR)               ^
W20150227-07:06:44.079(0)? (STDERR) Error: ER_NO_BINARY_LOGGING: You are not using binary logging
W20150227-07:06:44.079(0)? (STDERR)     at Query.Sequence._packetToError (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
W20150227-07:06:44.080(0)? (STDERR)     at Query.ErrorPacket (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
W20150227-07:06:44.080(0)? (STDERR)     at Protocol._parsePacket (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20150227-07:06:44.080(0)? (STDERR)     at Parser.write (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Parser.js:77:12)
W20150227-07:06:44.081(0)? (STDERR)     at Protocol.write (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:39:16)
W20150227-07:06:44.081(0)? (STDERR)     at Socket.<anonymous> (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/Connection.js:82:28)
W20150227-07:06:44.081(0)? (STDERR)     at Socket.emit (events.js:95:17)
W20150227-07:06:44.082(0)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:764:14)
W20150227-07:06:44.082(0)? (STDERR)     at Socket.emit (events.js:92:17)
W20150227-07:06:44.082(0)? (STDERR)     at emitReadable_ (_stream_readable.js:426:10)
W20150227-07:06:44.082(0)? (STDERR)     --------------------
W20150227-07:06:44.082(0)? (STDERR)     at Protocol._enqueue (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:135:48)
W20150227-07:06:44.083(0)? (STDERR)     at Connection.query (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/Connection.js:185:25)
W20150227-07:06:44.083(0)? (STDERR)     at ZongJi._findBinlogEnd (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:126:23)
W20150227-07:06:44.083(0)? (STDERR)     at nextMethod (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:67:22)
W20150227-07:06:44.083(0)? (STDERR)     at /home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:71:9
W20150227-07:06:44.083(0)? (STDERR)     at Query._callback (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:100:16)
W20150227-07:06:44.084(0)? (STDERR)     at Query.Sequence.end (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
W20150227-07:06:44.084(0)? (STDERR)     at Query.ErrorPacket (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
W20150227-07:06:44.085(0)? (STDERR)     at Protocol._parsePacket (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20150227-07:06:44.085(0)? (STDERR)     at Parser.write (/home/ubuntu/.meteor/packages/numtel_mysql/.0.1.0.1qlxii9++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Parser.js:77:12)





I have followed same steps as given in   https://github.com/numtel/mysql-live-select#installation 

and my.cnf file is 


#long_query_time = 2
#log-queries-not-using-indexes
#
# The following can be used as easy to replay backup logs or for replication.
# note: if you are setting up a replication slave, see README.Debian about
#       other settings you may need to change.
server-id               = 1
binlog_format           = row
log_bin                 = /var/log/mysql/mysql-bin.log
expire_logs_days        = 10
max_binlog_size         = 100M
binlog_do_db            = include_database_name
#binlog_ignore_db       = include_database_name
#
# * InnoDB
#
# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
#

**Comment by numtel** [comment]
@Topol @shipra123456 What version of mysql server are you running?

@shipra123456 You have the following line **not** commented out:
```
binlog_do_db            = include_database_name
```

Meaning that the binary log will only include the database named `include_database_name`. I don't think that's what's causing that error though.

**Comment by Topol** [comment]
I am using 5.6.23.....

**Comment by Topol** [comment]
I tried in ubuntu and it was working fine there. my mac is mountain lion....

**Comment by shipra123456** [comment]
my sql version is 5.5.41

**Comment by numtel** [comment]
I just installed OSX Yosemite in virtual box and have no problems with this package. Please ensure that your binary log is configured properly.

**Comment by rm3nchaca** [comment]
This is my my.cnf file for fedora 20, it's a very basic file, it's working fine.

When you get something like "ERROR! The server quit without updating PID file" just need to add permissions to the pid directory.

[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0
log_bin                        = mysql-bin
binlog_format                  = ROW
expire_logs_days               = 2
sync_binlog                    = 0
auto_increment_increment       = 10
auto_increment_offset          = 1

server-id                      = 1

log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid

[mysqld_safe]

#
# include all files from the config directory
#
!includedir /etc/my.cnf.d

**Comment by numtel** [comment]
Ok, I have come up with a package that integrates the MySQL server directly into Meteor making it very easy to get set up using this package. The binary log configuration is already in place, just set a port and you'll have a MySQL server that starts and stops with your Meteor app.

https://github.com/numtel/meteor-mysql-server

![easy-mysql](https://cloud.githubusercontent.com/assets/518698/7245069/eeaa4d34-e799-11e4-9620-7687683913f4.png)

**Comment by sajumani** [comment]
Am getting error

[Error] Mysql startup timeout!

**Comment by Topol** [comment]
Dear Ben

I tried doing this step in centos OS. Does it not work on centos OS.

**Comment by Topol** [comment]
I am getting the following error:

[ERROR] Fatal error: Please read "Security" section of the manual to find
out how to run mysqld as root!

But I am running the meteor command in root.

**Comment by Topol** [comment]
Nevermind it was a centos issue, fixed it

**Comment by Topol** [comment]
Dear Ben

I am trying to use your code inside the meteor server from a different
code. I can run your Leaderboard example but while deploying the same code
inside the server module I have to do these steps.  var LiveMysql =
Npm.require('mysql-live-select'); otherwise it does not recognize it.

Also I am getting the following error. Do you think I am doing something
wrong.

TypeError: string is not a function

W20151115-03:21:19.056(-7)? (STDERR)     at Handshake._callback
(/var/mobnode/node_modules/mysql-live-select/lib/LiveMysql.js:31:34)


The code is the following.

 var LiveMysql = Npm.require('mysql-live-select');

  var MysqlSubscription = Npm.require('mysql-live-select');

  players = new MysqlSubscription('allPlayers');

  myScore = new MysqlSubscription('playerScore', 'Maxwell');


var liveDb = new LiveMysql({

    host: 'localhost',

    // Port 3407 as specified in leaderboard.mysql.json

    // If using external MySQL server, the default port is 3306

    port: 3306,

    user: 'root',

    password: '****',

    database: 'leaderboard'

  });


  var closeAndExit = function() {

    liveDb.end();

    process.exit();

  };

  // Close connections on hot code push

  process.on('SIGTERM', closeAndExit);

  // Close connections on exit (ctrl + c)

  process.on('SIGINT', closeAndExit);

**Comment by Topol** [comment]
Dear Ben

I needed a confirmation on code. I think what you are doing is that you are
replicating a master-slave model and listening to the slave. So the first
question being, where is the slave maintained and who is managing it. Is it
the meteor itself.

The reason why I am asking is because, the meteor code works fine with
small databases but when I start using a relatively complex database, it
does not work. Can you suggest why this is happening.

Best
Arindam

**Comment by Topol** [comment]
For a different database I am getting this error. How do I fix this:

I20160731-03:53:24.876(-7)? Exception from sub playerScore id
ncqYPbS64WdSpcNE3 Error: triggers array required

I20160731-03:53:24.876(-7)?     at LiveMysql.select
(/root/.meteor/packages/numtel_mysql/.1.0.3.14i03be++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/LiveMysql.js:74:11)

I20160731-03:53:24.876(-7)?     at [object Object].Meteor.methods.incScore
[as _handler](leaderboard.js:90:1)

I20160731-03:53:24.876(-7)?     at maybeAuditArgumentChecks
(livedata_server.js:1698:12)

I20160731-03:53:24.877(-7)?     at [object Object]._.extend._runHandler
(livedata_server.js:1023:17)

I20160731-03:53:24.877(-7)?     at [object
Object]._.extend._startSubscription (livedata_server.js:842:9)

I20160731-03:53:24.877(-7)?     at [object
Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)

I20160731-03:53:24.877(-7)?     at livedata_server.js:548:43
